name: Testes automatizados

on:
  push:
    branches:
      - main 
jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r testes/requirements.txt  # Se você tiver um arquivo requirements.txt

      - name: Executar pytest
        run: pytest
