name: Testes automatizados

on:
  push:
    branches:
      - main 
      
jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
  
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r testes/requirements.txt
          pip install requests

      - name: install docker compose
        run: sudo apt install docker-compose
      - name: pull mysql image
        run: sudo docker pull mysql/mysql-server:5.7
      - name: list images
        run: sudo docker images
      - name: run mysql on docker
        run: sudo docker run --name=mysql  -p3306:3306 -e MYSQL_ROOT_PASSWORD=password --restart on-failure -d mysql/mysql-server:5.7
      - name: list containers
        run: sudo docker container ls
      - name: container started
        run: sudo docker ps

      - name: install node
        run: npm install
      
      - name: Executar pytest
        run: pytest
